### ISSUE TITLE
I'm unable to find out how to create a Calendar

### ISSUE THREAD

**Issue by Simon-Laux** [p3pch4t/calendar-webxdc#1]
I can't create a calendar which seems to be required to create an event.

Possible solutions:
- ask user to create calendar when the error comes up
- have a default calendar that is used by default
- have a button to create a calendar
- If there is already a way to create a calendar then make it more visible/obvious.

BTW nice webxdc app!

**Comment by Im-Beast** [comment]
Press the add button:
![image](https://github.com/user-attachments/assets/01a7f5ae-1dc3-4155-b52a-be6865884883)

Then you can add either event or calendar, select the latter:
![image](https://github.com/user-attachments/assets/77bfea65-4691-420f-90ce-97a2171e171c)

Fill the form:
![image](https://github.com/user-attachments/assets/67dd0004-5a1a-4205-af58-020afc4308fe)

Now you should have created calendar.

**Comment by Simon-Laux** [comment]
Thanks, I totally overlooked that.
Still would be nice if the app would force me to create a calendar first before letting me open the dialog/modal to add event.

**Comment by Im-Beast** [comment]
> Thanks, I totally overlooked that. Still would be nice if the app would force me to create a calendar first before letting me open the dialog/modal to add event.

That seems reasonable, i will check on it tommorow.
I will do either that or allow creating a new calendar from within the event modal when no calendars are present.
Thanks for insight and great words!
